[
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/laughing-skull/m%C3%A4rtini?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/101-227857393?namespace=profile-us",
    },
    name: "Märtini",
    id: 227857393,
    realm: {
      key: [Object],
      name: "Laughing Skull",
      id: 101,
      slug: "laughing-skull",
    },
    playable_class: { key: [Object], name: "Rogue", id: 4 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 30,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/gorgonnash/astryx?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/80-123026833?namespace=profile-us",
    },
    name: "Astryx",
    id: 123026833,
    realm: { key: [Object], name: "Gorgonnash", id: 80, slug: "gorgonnash" },
    playable_class: { key: [Object], name: "Hunter", id: 3 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 22,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/thunderhorn/arethusa?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/105-183349517?namespace=profile-us",
    },
    name: "Arethusa",
    id: 183349517,
    realm: {
      key: [Object],
      name: "Thunderhorn",
      id: 105,
      slug: "thunderhorn",
    },
    playable_class: { key: [Object], name: "Rogue", id: 4 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 30,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/sollinterieu?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-224205671?namespace=profile-us",
    },
    name: "Sollinterieu",
    id: 224205671,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Demon Hunter", id: 12 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 60,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solfeuduciel?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-235990675?namespace=profile-us",
    },
    name: "Solfeuduciel",
    id: 235990675,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Druid", id: 11 },
    playable_race: { key: [Object], name: "Night Elf", id: 4 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solnonne?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-235991343?namespace=profile-us",
    },
    name: "Solnonne",
    id: 235991343,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Monk", id: 10 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solfleche?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-235991363?namespace=profile-us",
    },
    name: "Solfleche",
    id: 235991363,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Hunter", id: 3 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/sollevente?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236314041?namespace=profile-us",
    },
    name: "Sollevente",
    id: 236314041,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Paladin", id: 2 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solsacerdote?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236793121?namespace=profile-us",
    },
    name: "Solsacerdote",
    id: 236793121,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Priest", id: 5 },
    playable_race: { key: [Object], name: "Lightforged Draenei", id: 30 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solpraesidia?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236796047?namespace=profile-us",
    },
    name: "Solpraesidia",
    id: 236796047,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Warrior", id: 1 },
    playable_race: { key: [Object], name: "Void Elf", id: 29 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 27,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solmaetcha?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236798355?namespace=profile-us",
    },
    name: "Solmaetcha",
    id: 236798355,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Evoker", id: 13 },
    playable_race: { key: [Object], name: "Dracthyr", id: 70 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/sollassiat?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236834050?namespace=profile-us",
    },
    name: "Sollassiat",
    id: 236834050,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Paladin", id: 2 },
    playable_race: { key: [Object], name: "Zandalari Troll", id: 31 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 22,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solemincer?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-236974520?namespace=profile-us",
    },
    name: "Solemincer",
    id: 236974520,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Rogue", id: 4 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solastary?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-237054268?namespace=profile-us",
    },
    name: "Solastary",
    id: 237054268,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Warlock", id: 9 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solmagus?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-239036817?namespace=profile-us",
    },
    name: "Solmagus",
    id: 239036817,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Mage", id: 8 },
    playable_race: { key: [Object], name: "Nightborne", id: 27 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 10,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/area-52/solfaimana?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1566-239056655?namespace=profile-us",
    },
    name: "Solfaimana",
    id: 239056655,
    realm: { key: [Object], name: "Area 52", id: 1566, slug: "area-52" },
    playable_class: { key: [Object], name: "Mage", id: 8 },
    playable_race: { key: [Object], name: "Night Elf", id: 4 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solpraesidia?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-233078040?namespace=profile-us",
    },
    name: "Solpraesidia",
    id: 233078040,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Warrior", id: 1 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solfaimana?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-233219466?namespace=profile-us",
    },
    name: "Solfaimana",
    id: 233219466,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Mage", id: 8 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 60,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/asteryx?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-233427430?namespace=profile-us",
    },
    name: "Asteryx",
    id: 233427430,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Shaman", id: 7 },
    playable_race: { key: [Object], name: "Draenei", id: 11 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 60,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solrinascita?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-233649625?namespace=profile-us",
    },
    name: "Solrinascita",
    id: 233649625,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Death Knight", id: 6 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 34,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solfleche?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-234223020?namespace=profile-us",
    },
    name: "Solfleche",
    id: 234223020,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Hunter", id: 3 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/thespiae?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-234328081?namespace=profile-us",
    },
    name: "Thespiae",
    id: 234328081,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Evoker", id: 13 },
    playable_race: { key: [Object], name: "Dracthyr", id: 70 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 60,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solsacerdote?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-234392215?namespace=profile-us",
    },
    name: "Solsacerdote",
    id: 234392215,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Priest", id: 5 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 63,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solshikari?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-234784634?namespace=profile-us",
    },
    name: "Solshikari",
    id: 234784634,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Demon Hunter", id: 12 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 60,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/skullcrusher/solfeuduciel?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/74-234784702?namespace=profile-us",
    },
    name: "Solfeuduciel",
    id: 234784702,
    realm: {
      key: [Object],
      name: "Skullcrusher",
      id: 74,
      slug: "skullcrusher",
    },
    playable_class: { key: [Object], name: "Druid", id: 11 },
    playable_race: { key: [Object], name: "Zandalari Troll", id: 31 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 70,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/galakrond/solistine?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/1581-173523899?namespace=profile-us",
    },
    name: "Solistine",
    id: 173523899,
    realm: { key: [Object], name: "Galakrond", id: 1581, slug: "galakrond" },
    playable_class: { key: [Object], name: "Rogue", id: 4 },
    playable_race: { key: [Object], name: "Void Elf", id: 29 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 45,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/illidan/solstrega?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/57-184689852?namespace=profile-us",
    },
    name: "Solstrega",
    id: 184689852,
    realm: { key: [Object], name: "Illidan", id: 57, slug: "illidan" },
    playable_class: { key: [Object], name: "Warlock", id: 9 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 50,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/illidan/solmarron?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/57-188805441?namespace=profile-us",
    },
    name: "Solmarron",
    id: 188805441,
    realm: { key: [Object], name: "Illidan", id: 57, slug: "illidan" },
    playable_class: { key: [Object], name: "Warrior", id: 1 },
    playable_race: { key: [Object], name: "Mag'har Orc", id: 36 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 30,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/illidan/asteryx?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/57-201291838?namespace=profile-us",
    },
    name: "Asteryx",
    id: 201291838,
    realm: { key: [Object], name: "Illidan", id: 57, slug: "illidan" },
    playable_class: { key: [Object], name: "Shaman", id: 7 },
    playable_race: { key: [Object], name: "Goblin", id: 9 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 51,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/kiljaeden/academyx?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/9-120671618?namespace=profile-us",
    },
    name: "Academyx",
    id: 120671618,
    realm: { key: [Object], name: "Kil'jaeden", id: 9, slug: "kiljaeden" },
    playable_class: { key: [Object], name: "Warrior", id: 1 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 30,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/kiljaeden/optyx?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/9-120916601?namespace=profile-us",
    },
    name: "Optyx",
    id: 120916601,
    realm: { key: [Object], name: "Kil'jaeden", id: 9, slug: "kiljaeden" },
    playable_class: { key: [Object], name: "Mage", id: 8 },
    playable_race: { key: [Object], name: "Blood Elf", id: 10 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "HORDE", name: "Horde" },
    level: 5,
  },
  {
    character: {
      href: "https://us.api.blizzard.com/profile/wow/character/spinebreaker/mimiec459d3?namespace=profile-us",
    },
    protected_character: {
      href: "https://us.api.blizzard.com/profile/user/wow/protected-character/82-205325753?namespace=profile-us",
    },
    name: "MimieC459D3",
    id: 205325753,
    realm: {
      key: [Object],
      name: "Spinebreaker",
      id: 82,
      slug: "spinebreaker",
    },
    playable_class: { key: [Object], name: "Druid", id: 11 },
    playable_race: { key: [Object], name: "Night Elf", id: 4 },
    gender: { type: "FEMALE", name: "Female" },
    faction: { type: "ALLIANCE", name: "Alliance" },
    level: 1,
  },
];
